In [1]:
# Suport Vector Mechine (SVM)

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
# Importing the dataset

df = pd.read_csv('datasets/shipping.csv')
df.head()

ID Warehouse_block Mode_of_Shipment  Customer_care_calls  Customer_rating  \
0   1               D           Flight                    4                2   
1   2               F           Flight                    4                5   
2   3               A           Flight                    2                2   
3   4               B           Flight                    3                3   
4   5               C           Flight                    2                2   

   Cost_of_the_Product  Prior_purchases Product_importance Gender  \
0                  177                3                low      F   
1                  216                2                low      M   
2                  183                4                low      M   
3                  176                4             medium      M   
4                  184                3             medium      F   

   Discount_offered  Weight_in_gms  Reached.on.Time_Y.N  
0                44           1233                    1  
1                59           3088                    1  
2                48           3374                    1  
3                10           1177                    1  
4                46           2484                    1

In [3]:

# Convert Warehouse_block to numerical
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()


df['Warehouse_block_Encoded'] = label_encoder.fit_transform(df['Warehouse_block'])

# Convert Mode_of_Shipment to numerical

df['Mode_of_Shipment_Encoded'] = label_encoder.fit_transform(df['Mode_of_Shipment'])

# Convert Product_importance to numerical
df['Product_importance_Encoded'] = label_encoder.fit_transform(df['Product_importance'])

df['Gender_Encoded'] = label_encoder.fit_transform(df['Gender'])

df.head()


ID Warehouse_block Mode_of_Shipment  Customer_care_calls  Customer_rating  \
0   1               D           Flight                    4                2   
1   2               F           Flight                    4                5   
2   3               A           Flight                    2                2   
3   4               B           Flight                    3                3   
4   5               C           Flight                    2                2   

   Cost_of_the_Product  Prior_purchases Product_importance Gender  \
0                  177                3                low      F   
1                  216                2                low      M   
2                  183                4                low      M   
3                  176                4             medium      M   
4                  184                3             medium      F   

   Discount_offered  Weight_in_gms  Reached.on.Time_Y.N  \
0                44           1233                    1   
1                59           3088                    1   
2                48           3374                    1   
3                10           1177                    1   
4                46           2484                    1   

   Warehouse_block_Encoded  Mode_of_Shipment_Encoded  \
0                        3                         0   
1                        4                         0   
2                        0                         0   
3                        1                         0   
4                        2                         0   

   Product_importance_Encoded  Gender_Encoded  
0                           1               0  
1                           1               1  
2                           1               1  
3                           2               1  
4                           2               0

In [4]:
# Drop the columns that are not needed
df = df.drop(['Warehouse_block', 'Mode_of_Shipment', 'Product_importance', 'Gender'], axis=1)

correlation = df.corr()
correlation

ID  Customer_care_calls  Customer_rating  \
ID                          1.000000             0.188998        -0.005722   
Customer_care_calls         0.188998             1.000000         0.012209   
Customer_rating            -0.005722             0.012209         1.000000   
Cost_of_the_Product         0.196791             0.323182         0.009270   
Prior_purchases             0.145369             0.180771         0.013179   
Discount_offered           -0.598278            -0.130750        -0.003124   
Weight_in_gms               0.278312            -0.276615        -0.001897   
Reached.on.Time_Y.N        -0.411822            -0.067126         0.013119   
Warehouse_block_Encoded     0.000070             0.014496         0.010169   
Mode_of_Shipment_Encoded   -0.002459            -0.020164         0.001679   
Product_importance_Encoded  0.029081             0.006273         0.003157   
Gender_Encoded             -0.001695             0.002545         0.002775   

                            Cost_of_the_Product  Prior_purchases  \
ID                                     0.196791         0.145369   
Customer_care_calls                    0.323182         0.180771   
Customer_rating                        0.009270         0.013179   
Cost_of_the_Product                    1.000000         0.123676   
Prior_purchases                        0.123676         1.000000   
Discount_offered                      -0.138312        -0.082769   
Weight_in_gms                         -0.132604        -0.168213   
Reached.on.Time_Y.N                   -0.073587        -0.055515   
Warehouse_block_Encoded               -0.006679        -0.005262   
Mode_of_Shipment_Encoded               0.006681        -0.001640   
Product_importance_Encoded             0.006366         0.003662   
Gender_Encoded                         0.019759        -0.009395   

                            Discount_offered  Weight_in_gms  \
ID                                 -0.598278       0.278312   
Customer_care_calls                -0.130750      -0.276615   
Customer_rating                    -0.003124      -0.001897   
Cost_of_the_Product                -0.138312      -0.132604   
Prior_purchases                    -0.082769      -0.168213   
Discount_offered                    1.000000      -0.376067   
Weight_in_gms                      -0.376067       1.000000   
Reached.on.Time_Y.N                 0.397108      -0.268793   
Warehouse_block_Encoded             0.009569       0.004086   
Mode_of_Shipment_Encoded            0.009364      -0.000797   
Product_importance_Encoded         -0.006251       0.001652   
Gender_Encoded                     -0.011777       0.003573   

                            Reached.on.Time_Y.N  Warehouse_block_Encoded  \
ID                                    -0.411822                 0.000070   
Customer_care_calls                   -0.067126                 0.014496   
Customer_rating                        0.013119                 0.010169   
Cost_of_the_Product                   -0.073587                -0.006679   
Prior_purchases                       -0.055515                -0.005262   
Discount_offered                       0.397108                 0.009569   
Weight_in_gms                         -0.268793                 0.004086   
Reached.on.Time_Y.N                    1.000000                 0.005214   
Warehouse_block_Encoded                0.005214                 1.000000   
Mode_of_Shipment_Encoded              -0.000535                 0.000617   
Product_importance_Encoded            -0.023483                 0.004260   
Gender_Encoded                         0.004689                -0.003700   

                            Mode_of_Shipment_Encoded  \
ID                                         -0.002459   
Customer_care_calls                        -0.020164   
Customer_rating                             0.001679   
Cost_of_the_Product                         0.006681   
Prior_purchases                            -0

In [5]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing data
X = df.drop(['Reached.on.Time_Y.N', 'Discount_offered', 'Customer_care_calls', 'Customer_rating', 'Weight_in_gms'], axis=1)
print(X)

y = df['Customer_care_calls']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

          ID  Cost_of_the_Product  Prior_purchases  Warehouse_block_Encoded  \
0          1                  177                3                        3   
1          2                  216                2                        4   
2          3                  183                4                        0   
3          4                  176                4                        1   
4          5                  184                3                        2   
...      ...                  ...              ...                      ...   
10994  10995                  252                5                        0   
10995  10996                  232                5                        1   
10996  10997                  242                5                        2   
10997  10998                  223                6                        4   
10998  10999                  155                5                        3   

       Mode_of_Shipment_Encoded  Product_importance

In [6]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Fitting SVM to the Training set
from sklearn.svm import SVC

classifier = SVC(kernel='linear', random_state=0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)


[[  0  54  67   0   0   0]
 [  0 288 384   0   0   0]
 [  0 249 453   0   0   0]
 [  0 144 313   0   0   0]
 [  0  35 170   0   0   0]
 [  0   3  40   0   0   0]]


In [ ]:
# Print the accuracy

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print(accuracy)